### ISSUE TITLE
Error whe starts activity

### ISSUE THREAD

**Issue by kenumir** [kenumir/MaterialSettings#2]
All settings is set like in demo app. Error occurs when starting settings activity.

``` java
03-25 10:19:54.474  17243-17243/com.sampleapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.hv.sampleapp , PID: 17243
    java.lang.NoSuchFieldError: No static field material_settings_top_frame of type I in class Lcom/kenumir/materialsettings/R$id; or its superclasses (declaration of 'com.kenumir.materialsettings.R$id' appears in /data/app/app-1/base.apk)
            at com.kenumir.materialsettings.MaterialSettings.onCreate(MaterialSettings.java:59)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by janheinrichmerker** [comment]
This should be fixed by the library authors by simply prefixing their resources. Just name the file `ms_...` to avoid problems with overwritten library files.
