### ISSUE TITLE
I copy the code to my project,but it doesn't work,my support:appcompat-v7:22.1.1'

### ISSUE THREAD

**Issue by yanbing177** [kenumir/MaterialSettings#6]
java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.liuyanbing.surveyor/cn.liuyanbing.surveyor.activity.SettingsActivity}: java.lang.RuntimeException: Binary XML file line #2: You must supply a layout_width attribute.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2190)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2239)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5047)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Binary XML file line #2: You must supply a layout_width attribute.
            at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
            at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:5948)
            at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6117)
            at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1831)
            at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1743)
            at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:58)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
            at com.kenumir.materialsettings.MaterialSettingsItem.initView(MaterialSettingsItem.java:31)
            at com.kenumir.materialsettings.MaterialSettingsItem.getView(MaterialSettingsItem.java:36)
            at com.kenumir.materialsettings.MaterialSettings.addItem(MaterialSettings.java:131)
            at cn.liuyanbing.surveyor.activity.SettingsActivity.onCreate(SettingsActivity.java:20)
            at android.app.Activity.performCreate(Activity.java:5249)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2154)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2239)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5047)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by kenumir** [comment]
Propably you not set layout_width attribute in your xml layout

**Comment by ihgoo** [comment]
The Android manifest shoud add theme in the activity node,like this:

```
<activity
            android:name=".ui.SettingActivity"
            android:theme="@style/MaterialSettingsTheme">
</activity>
```

**Comment by WeihuaGu** [comment]
@ihgoo  I have added the ' android:theme="@style/MaterialSettingsTheme' in manifest file .
but it doesn't work still
```
Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: You must supply a layout_width attribute.
                                                                    Caused by: java.lang.UnsupportedOperationException: Binary XML file line #2: You must supply a layout_width attribute.
```

**Comment by WeihuaGu** [comment]
@kenumir  I added the ' android:theme="@style/MaterialSettingsTheme' in manifest file
and in my layout don't have a xml file named "activity_material_settings.xml"

and I use the version is 1.2.2 by gradle.

the error still
